/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author edfer
 */
public class RegisterProduct extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterProduct.class.getName());

    /**
     * Creates new form RegisterProduct
     */
    public RegisterProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stateButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        formContainer = new javax.swing.JPanel();
        movementLabel = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        codeInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        categorySelect = new javax.swing.JComboBox<>();
        purchaseCheckBox = new javax.swing.JCheckBox();
        saleCheckBox = new javax.swing.JCheckBox();
        giftCheckBox = new javax.swing.JCheckBox();
        priceInput = new javax.swing.JTextField();
        inactiveRadioButton = new javax.swing.JRadioButton();
        activeRadioButton = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product registration");
        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));

        mainPanel.setBackground(new java.awt.Color(248, 250, 252));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 1, true));
        mainPanel.setPreferredSize(new java.awt.Dimension(656, 440));

        formTitle.setBackground(new java.awt.Color(248, 250, 252));
        formTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        formTitle.setForeground(new java.awt.Color(0, 0, 0));
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("Product registration");
        formTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 2, true));

        formContainer.setBackground(new java.awt.Color(248, 250, 252));
        formContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 2, true));

        movementLabel.setBackground(new java.awt.Color(248, 250, 252));
        movementLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        movementLabel.setForeground(new java.awt.Color(51, 51, 51));
        movementLabel.setText("Movement");
        movementLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        codeLabel.setBackground(new java.awt.Color(248, 250, 252));
        codeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        codeLabel.setForeground(new java.awt.Color(51, 51, 51));
        codeLabel.setText("Code ");
        codeLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        nameLabel.setBackground(new java.awt.Color(248, 250, 252));
        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("Name");
        nameLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        categoryLabel.setBackground(new java.awt.Color(248, 250, 252));
        categoryLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(51, 51, 51));
        categoryLabel.setText("Category");
        categoryLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        priceLabel.setBackground(new java.awt.Color(248, 250, 252));
        priceLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(51, 51, 51));
        priceLabel.setText("Price");
        priceLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        statusLabel.setBackground(new java.awt.Color(248, 250, 252));
        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(51, 51, 51));
        statusLabel.setText("State");
        statusLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(248, 250, 252), new java.awt.Color(248, 250, 252), new java.awt.Color(238, 238, 238), new java.awt.Color(238, 238, 238)));

        codeInput.setBackground(new java.awt.Color(238, 238, 238));
        codeInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        codeInput.setForeground(new java.awt.Color(51, 51, 51));
        codeInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        codeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeInputActionPerformed(evt);
            }
        });

        nameInput.setBackground(new java.awt.Color(238, 238, 238));
        nameInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nameInput.setForeground(new java.awt.Color(51, 51, 51));
        nameInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        categorySelect.setBackground(new java.awt.Color(238, 238, 238));
        categorySelect.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        categorySelect.setForeground(new java.awt.Color(51, 51, 51));
        categorySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a category", "Computers & Laptops", "Audio equipment", "Desk accessories", "Special combinations" }));
        categorySelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        categorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySelectActionPerformed(evt);
            }
        });

        purchaseCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        purchaseCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        purchaseCheckBox.setText("Purchase");
        purchaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseCheckBoxActionPerformed(evt);
            }
        });

        saleCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        saleCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        saleCheckBox.setText("Sale");
        saleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleCheckBoxActionPerformed(evt);
            }
        });

        giftCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        giftCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        giftCheckBox.setText("Gift");
        giftCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giftCheckBoxActionPerformed(evt);
            }
        });

        priceInput.setBackground(new java.awt.Color(238, 238, 238));
        priceInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        priceInput.setForeground(new java.awt.Color(51, 51, 51));
        priceInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        priceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceInputActionPerformed(evt);
            }
        });

        inactiveRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        stateButtonGroup.add(inactiveRadioButton);
        inactiveRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        inactiveRadioButton.setText("Inactive");
        inactiveRadioButton.setActionCommand("active");
        inactiveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactiveRadioButtonActionPerformed(evt);
            }
        });

        activeRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        stateButtonGroup.add(activeRadioButton);
        activeRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        activeRadioButton.setText("Active");
        activeRadioButton.setActionCommand("active");
        activeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeRadioButtonActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 11, 85));
        cancel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codeInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                        .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(categorySelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceInput))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(movementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(purchaseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saleCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(giftCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(activeRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(inactiveRadioButton))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        formContainerLayout.setVerticalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giftCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inactiveRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        System.out.println("Clic desde el boton save");
    }//GEN-LAST:event_saveActionPerformed

    private void activeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeRadioButtonActionPerformed

    private void priceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceInputActionPerformed

    private void giftCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giftCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giftCheckBoxActionPerformed

    private void saleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleCheckBoxActionPerformed

    private void purchaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseCheckBoxActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void codeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeInputActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void categorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorySelectActionPerformed

    private void inactiveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactiveRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inactiveRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioButton;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JComboBox<String> categorySelect;
    private javax.swing.JTextField codeInput;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JPanel formContainer;
    private javax.swing.JLabel formTitle;
    private javax.swing.JCheckBox giftCheckBox;
    private javax.swing.JRadioButton inactiveRadioButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel movementLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField priceInput;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JCheckBox purchaseCheckBox;
    private javax.swing.JCheckBox saleCheckBox;
    private javax.swing.JButton save;
    private javax.swing.ButtonGroup stateButtonGroup;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
